version: "3.7"

services:
  site:
    image: site-nginx:local
    ports:
      - 80:80
    networks:
      - site-network


networks:
  site-network:
    driver: bridge
    ipam:
      driver: default
